scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['172.31.22.51:9090']
        labels:
          application: 'My Spring Boot Application'
